env -i ./../minishell puis echo  $SHLVL
env -i ./../minishell puis echo  $SHLVL
env -i ./../minishell puis echo  $SHLVL
env -i ./../minishell puis echo  $SHLVL
env -i ./../minishell puis echo  $SHLVL
env -i ./../minishell puis echo  $SHLVL
env -i ./../minishell puis echo  $SHLVL
env -i ./../minishell puis echo  $SHLVL
env -i ./../minishell puis echo  $SHLVL
env -i ./../minishell puis echo  $SHLVL
env -i ./../minishell puis echo  $SHLVL
