> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
> test | echo blabla; cat test; rm -rf test
