ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?
ls bonjour ; echo  $?

