cat Makefile | grep pr | head -n 5 | hello
cat Makefile | grep pr | head -n 5 | hello
cat Makefile | grep pr | head -n 5 | hello
cat Makefile | grep pr | head -n 5 | hello
cat Makefile | grep pr | head -n 5 | hello
cat Makefile | grep pr | head -n 5 | hello
cat Makefile | grep pr | head -n 5 | hello
cat Makefile | grep pr | head -n 5 | hello
cat Makefile | grep pr | head -n 5 | hello
