
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
echo $hfkdghldf$PWD
