echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
echo $USER$var\$USER$USER\$USERtest$USER            
