echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
echo bonjour \; ls                      
