echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
echo -n -n -nnnn -nnnnm ; echo a
