echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
echo -n -nnn hello -n ; echo a
